version: '3.3'
services:
    api: 
        build: 
            context: ./
            dockerfile: ./docker/${ENV}/Dockerfile
        image: libquality:1.0.0
        container_name: libquality-api
        ports: 
            - "3000:3000"
        restart: always
        links: 
            - mysqldb
            # - redis
        depends_on: 
            - mysqldb
            # - redis
    mysqldb:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        container_name: "libquality-db"
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: libquality
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/:/var/lib/mysql
    # redis:
    #     image: redis
    #     container_name: "redis"
    #     ports:
    #         - "6379:6379"
